name: "Publish Logseq Graph"

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  publish-logseq:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish Logseq graph
        uses: logseq/publish-spa@v0.3.0
        with:
          version: 0.10.9

      - name: Add a .nojekyll file
        run: touch $GITHUB_WORKSPACE/www/.nojekyll

      - name: Deploy to gh-pages branch
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: www
